### ISSUE TITLE
Issue loading plugin after most recent update

### ISSUE THREAD

**Issue by jeffyor** [gh640/chrome-extension-extension-switch-v2#4]
The plugin doesn't work anymore since the most recent update. See here - https://share.cleanshot.com/Vpkt4hRY

**Comment by gh640** [comment]
Thank you for sharing the issue! I'm sorry for the inconvenience.

In my environment ↓ , the latest `2.0.1` and `2.0.0` work well and I failed to reproduce the problem.

My environment:

- Extension Switch: `2.0.1`
- Chrome: Version 123.0.6312.124 (Official Build) (arm64)
- OS: macOS Sonoma Version 14.4.1 (23E224)

Could you please check if there are any errors when the pop-up window doesn't open? If there are any, I would appreciate it if you could share the entire message.

https://developer.chrome.com/docs/extensions/get-started/tutorial/debug#debug_popup

![image](https://github.com/gh640/chrome-extension-extension-switch-v2/assets/3532528/c44e2e92-750a-4ef3-9471-4d50e3d53554)

**Comment by jeffyor** [comment]
See the attached.

**Comment by gh640** [comment]
> See the attached.

Where can I see it?

——-

I received a message from a different user and was shared an error message she or he got. I tried to resolve the issue in #5 and pushed a new version `2.0.2` with the fix. It might be the same issue.

**Comment by jeffyor** [comment]
Sorry I just replied to the email I got with the attachment but must not work here’s a link….Screenshot 2024-04-17 at 13.36.53.pngdrive.google.comOn Apr 18, 2024, at 6:09 AM, Goto Hayato ***@***.***> wrote:﻿

See the attached.

Where can I see it?
——-
I received a message from a different user and was shared an error message she or he got. I tried to resolve the issue in #5 and pushed a new version 2.0.2 with the fix. It might be the same issue.

**Comment by gh640** [comment]
Thanks! The link is not a URL in my side…

https://github.com/gh640/chrome-extension-extension-switch-v2/issues/4#issuecomment-2063515898

It might have been stripped?

**Comment by jeffyor** [comment]
![Screenshot 2024-04-17 at 13 36 53](https://github.com/gh640/chrome-extension-extension-switch-v2/assets/24259999/4cd16191-2eb1-4718-97da-af20bd51897c)

Well, I guess I'm learning about some of the limitations of the GitHub notification system. I just logged in and commented directly. Sorry about that.

**Comment by gh640** [comment]
Thank you! I can see the attached image this time :D

It seems an error in `utils-xxx.js`:

> Cannot read properties of undefined (reading 'length')

Given that #5 had a similar error message, I suspect that the issue should be resolved once the latest version `2.0.2` is downloaded to your environment.

Please let me know if the problem persists after the extension is updated to the version `2.0.2`.

Thanks!

**Comment by jeffyor** [comment]
Yes, it worked! Thank you!

**Comment by gh640** [comment]
That’s wonderful to hear! Thank you for your assistance :)
